# Generated by Django 6.0.4 on 2026-10-05 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0008_etiquetas_dinamicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_corrida', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resumen', models.DateField(blank=True, null=True)),
                ('ultimo_reporte_clientes', models.CharField(blank=True, max_length=7)),
                ('ultimo_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarea_asignada', 'Tarea asignada'), ('tarea_estado', 'Cambio de estado de una tarea'), ('tarea_hecha', 'Tarea terminada'), ('deadline_manana', 'Vence mañana'), ('deadline_hoy', 'Vence hoy'), ('tarea_vencida', 'Tarea vencida'), ('servicio', 'Pago de servicio'), ('aporte', 'Aporte a un servicio'), ('cliente', 'Clientes'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('clave', models.CharField(blank=True, max_length=160)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('email_enviado', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='equipo.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada', '-id'],
                'indexes': [models.Index(fields=['usuario', 'leida_en'], name='notificacio_usuario_9ff5cf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave', ''), _negated=True), fields=('usuario', 'clave'), name='notificacion_clave_unica')],
            },
        ),
    ]
