# Generated by Django 6.0.4 on 2026-04-27 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('rol', models.CharField(blank=True, max_length=120)),
                ('color', models.CharField(default='#7c6fff', max_length=12)),
                ('contactos', models.JSONField(default=list)),
                ('notas', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='equipo.persona')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='equipo.tarea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('persona', 'tarea'), name='unique_asignacion_persona_tarea')],
            },
        ),
    ]
