# Generated by Django 6.0.4 on 2026-09-29 00:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipo', '0001_initial'),
        ('finanzas', '0004_categoria_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['estado', 'fecha_limite', 'titulo']},
        ),
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='alias_cbu',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='persona',
            name='cuit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='honorario_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_vinculo',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('empleado', 'Empleado'), ('socio', 'Socio')], default='freelancer', max_length=12),
        ),
        migrations.AddField(
            model_name='tarea',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('hecha', 'Hecha')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=6),
        ),
        migrations.AlterField(
            model_name='persona',
            name='contactos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AsignacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=80)),
                ('modalidad', models.CharField(choices=[('fijo', 'Fijo mensual'), ('porcentaje', 'Porcentaje del fee'), ('por_pieza', 'Por pieza')], default='fijo', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='clientes.cliente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_cliente', to='equipo.persona')),
            ],
            options={
                'ordering': ['cliente__nombre', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('concepto', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('asignacion', 'Asignación a cliente'), ('base', 'Honorario base'), ('manual', 'Manual')], default='manual', max_length=12)),
                ('monto_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20)),
                ('comprobante', models.CharField(blank=True, max_length=80)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='equipo.asignacioncliente')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='clientes.cliente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='equipo.persona')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion', to='finanzas.transaccion')),
            ],
            options={
                'ordering': ['-periodo', 'persona__nombre'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('monto_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipo.liquidacion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacioncliente',
            constraint=models.UniqueConstraint(fields=('persona', 'cliente', 'rol'), name='unique_asignacion_cliente_rol'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['periodo', 'persona'], name='liq_periodo_persona_idx'),
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(condition=models.Q(('asignacion__isnull', False)), fields=('asignacion', 'periodo'), name='unique_liquidacion_asignacion_periodo'),
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'base')), fields=('persona', 'periodo'), name='unique_liquidacion_base_periodo'),
        ),
    ]
