# Generated by Django 6.0.4 on 2026-09-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_tarea_options_persona_activo_persona_alias_cbu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='honorario_base',
        ),
    ]
