# Generated by Django 6.0.4 on 2026-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_quitar_honorario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='notion_user_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='tarea',
            name='notion_huella',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tarea',
            name='notion_page_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Por hacer'), ('en_curso', 'En progreso'), ('bloqueada', 'Bloqueada'), ('en_revision', 'En revisión'), ('hecha', 'Hecha')], default='pendiente', max_length=12),
        ),
    ]
