# Generated by Django 6.0.4 on 2026-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0004_notion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
