# Generated by Django 6.0.4 on 2026-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0005_tarea_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tarea',
            name='google_huella',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
