# Generated by Django 6.0.4 on 2026-09-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_google_color'),
        ('equipo', '0006_tarea_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='etiqueta',
            field=models.CharField(choices=[('historias', 'Historias'), ('posteos', 'Posteos'), ('edicion', 'Edición')], default='historias', max_length=12),
        ),
        migrations.AddField(
            model_name='tarea',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TareaRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('dias', models.JSONField(default=list)),
                ('por_dia', models.PositiveSmallIntegerField(default=1)),
                ('etiqueta', models.CharField(choices=[('historias', 'Historias'), ('posteos', 'Posteos'), ('edicion', 'Edición')], default='historias', max_length=12)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=6)),
                ('activa', models.BooleanField(default=True)),
                ('generada_hasta', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrentes', to='clientes.cliente')),
                ('personas', models.ManyToManyField(blank=True, related_name='recurrentes', to='equipo.persona')),
            ],
            options={
                'ordering': ['cliente__nombre', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='recurrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='equipo.tarearecurrente'),
        ),
    ]
