# Generated by Django 6.0.4 on 2026-10-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0007_tareas_recurrentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='notion_privada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='etiqueta',
            field=models.CharField(default='historias', max_length=40),
        ),
        migrations.AlterField(
            model_name='tarearecurrente',
            name='etiqueta',
            field=models.CharField(default='historias', max_length=40),
        ),
    ]
