# Generated by Django 6.0.4 on 2026-10-05 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_pasoonboarding_cliente_drive_folder_id_and_more'),
        ('equipo', '0008_etiquetas_dinamicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarea',
            name='paso_onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.pasoonboarding'),
        ),
    ]
