# Generated by Django 6.0.4 on 2026-09-29 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisstats',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='analisisstats',
            name='estado',
            field=models.CharField(choices=[('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='listo', max_length=12),
        ),
        migrations.AddField(
            model_name='analisisstats',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analisisstats',
            name='periodo_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analisisstats',
            name='periodo_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisisstats',
            name='metricas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='analisisstats',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis', to=settings.AUTH_USER_MODEL),
        ),
    ]
