# Generated by Django 6.0.4 on 2026-04-27 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('ingreso', 'ingreso'), ('egreso', 'egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='finanzas.transaccion')),
            ],
        ),
    ]
