# Generated by Django 6.0.4 on 2026-09-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('ingreso', 'ingreso'), ('egreso', 'egreso')], max_length=10)),
                ('color', models.CharField(default='#7c6fff', max_length=12)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['tipo', 'orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tipo'), name='unique_categoria_nombre_tipo')],
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='categoria_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finanzas.categoria'),
        ),
    ]
