# Generated by Django 6.0.4 on 2026-09-29 00:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipo', '0002_alter_tarea_options_persona_activo_persona_alias_cbu_and_more'),
        ('finanzas', '0004_categoria_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntotransaccion',
            name='tipo_contenido',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='comprobante',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='equipo.persona'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha', 'tipo'], name='tx_fecha_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cliente', 'fecha'], name='tx_cliente_fecha_idx'),
        ),
    ]
