# Generated by Django 6.0.4 on 2026-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoNotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_token', models.CharField(blank=True, max_length=200)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('ultima_sync_completa', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('ultimo_error_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
