# Generated by Django 6.0.4 on 2026-09-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='equipo.persona'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('equipo', 'Equipo')], default='equipo', max_length=10),
        ),
    ]
