# Generated by Django 6.0.4 on 2026-09-29 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuarios_existentes_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gmail_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_client_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_connected',
        ),
        migrations.CreateModel(
            name='CuentaGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('refresh_token', models.TextField()),
                ('scopes', models.TextField(blank=True)),
                ('conectada_en', models.DateTimeField(auto_now=True)),
                ('conectada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Google',
                'verbose_name_plural': 'Cuenta de Google',
            },
        ),
    ]
