# Generated by Django 6.0.4 on 2026-10-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif_email',
            field=models.BooleanField(default=True),
        ),
    ]
