# Generated by Django 6.0.4 on 2026-09-29 00:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_adjuntotransaccion_tipo_contenido_and_more'),
        ('servicios', '0002_servicio_fecha_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzas.categoria'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dia_vencimiento',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='servicio',
            name='generar_egreso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='periodicidad',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=12),
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='detalle',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='metodo',
            field=models.CharField(choices=[('sin_division', 'Sin división'), ('partes-iguales', 'Partes iguales'), ('porcentaje', 'Por porcentaje'), ('personalizado', 'Monto personalizado')], default='sin_division', max_length=24),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='mi_parte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicios.servicio')),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_servicio', to='finanzas.transaccion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('servicio', 'periodo'), name='unique_pago_servicio_periodo')],
            },
        ),
    ]
