# Generated by Django 6.0.4 on 2026-10-05 08:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0008_etiquetas_dinamicas'),
        ('servicios', '0004_migrar_servicios_a_suscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='dias_aviso',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='servicio',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_que_paga', to='equipo.persona'),
        ),
        migrations.CreateModel(
            name='AvisoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('aporte', 'Aporte')], max_length=6)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('vencimiento', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_servicio', to='equipo.persona')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='servicios.servicio')),
                ('tarea', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aviso_servicio', to='equipo.tarea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('servicio', 'periodo', 'persona', 'tipo'), name='aviso_servicio_unico')],
            },
        ),
    ]
