# Generated by Django 6.0.4 on 2026-09-29 00:13

import apps.core.utils
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('finanzas', '0004_categoria_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('razon_social', models.CharField(blank=True, max_length=160)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('rubro', models.CharField(blank=True, max_length=80)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('baja', 'Baja')], default='activo', max_length=10)),
                ('fecha_alta', models.DateField(default=apps.core.utils.today)),
                ('color', models.CharField(default='#4fffb0', max_length=12)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unico', 'Pago único')], default='mensual', max_length=12)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('fecha_inicio', models.DateField(default=apps.core.utils.today)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzas.categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_responsable', to='equipo.persona')),
            ],
            options={
                'ordering': ['cliente__nombre', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='AjustePrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='clientes.contrato')),
            ],
            options={
                'ordering': ['-fecha_desde', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vencimiento', models.DateField()),
                ('monto_cobrado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('otro', 'Otro')], max_length=20)),
                ('comprobante', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='clientes.cliente')),
                ('transaccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobro', to='finanzas.transaccion')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros', to='clientes.contrato')),
            ],
            options={
                'ordering': ['vencimiento', 'cliente__nombre'],
                'indexes': [models.Index(fields=['periodo', 'estado'], name='cobro_periodo_estado_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('contrato__isnull', False)), fields=('contrato', 'periodo'), name='unique_cobro_contrato_periodo')],
            },
        ),
    ]
