# Generated by Django 6.0.4 on 2026-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_migrar_clientes_mensuales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notion_page_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
