# Generated by Django 6.0.4 on 2026-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_notion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='google_color',
            field=models.CharField(blank=True, choices=[('1', 'Lavanda'), ('2', 'Salvia'), ('3', 'Uva'), ('4', 'Flamenco'), ('5', 'Banana'), ('6', 'Mandarina'), ('7', 'Pavo real'), ('8', 'Grafito'), ('9', 'Arándano'), ('10', 'Albahaca'), ('11', 'Tomate')], max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
