# Generated by Django 6.0.4 on 2026-10-05 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_google_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('rol', models.CharField(choices=[('admin', 'Socios'), ('cm', 'Community manager'), ('editor', 'Editor de video'), ('disenio', 'Diseño'), ('foto', 'Fotografía / Filmmaker')], default='cm', max_length=10)),
                ('dias_desde_alta', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(90)])),
                ('etiqueta', models.CharField(default='reuniones', max_length=40)),
                ('accion', models.CharField(blank=True, choices=[('', 'Tarea'), ('drive', 'Crear la carpeta de Drive')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='cliente',
            name='onboarding_iniciado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
