# Generated by Django 6.0.4 on 2026-10-05 08:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_plantilla_onboarding_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEnvios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reporte', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('dias_antes', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(15)])),
                ('dias_despues', models.CharField(default='3,7', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='recordatorios_cobro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reporte_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EnvioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte', 'Reporte mensual'), ('recordatorio', 'Recordatorio de cobro')], max_length=12)),
                ('periodo', models.CharField(max_length=7)),
                ('clave', models.CharField(blank=True, max_length=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('error', 'Error'), ('descartado', 'Descartado')], default='borrador', max_length=10)),
                ('para', models.CharField(blank=True, max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('html', models.TextField()),
                ('error', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='clientes.cliente')),
                ('cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='clientes.cobro')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'reporte')), fields=('cliente', 'periodo'), name='envio_reporte_unico'), models.UniqueConstraint(condition=models.Q(('tipo', 'recordatorio'), models.Q(('clave', 'manual'), _negated=True)), fields=('cobro', 'clave'), name='envio_recordatorio_unico')],
            },
        ),
    ]
