# Generated by Django 6.0.4 on 2026-10-05 09:50

from django.db import migrations, models

VIEJO = ('Crear la carpeta de Drive del cliente', 'Con subcarpetas Brief, Material crudo, Ediciones, Diseños y Reportes.')
NUEVO = ('Carpeta de Drive del cliente', 'En Mi unidad → CLIENTES. Si ya existe una con su nombre se vincula; si no, se crea.')


def actualizar(apps, schema_editor):
    PasoOnboarding = apps.get_model('clientes', 'PasoOnboarding')
    PasoOnboarding.objects.filter(accion='drive', titulo=VIEJO[0]).update(titulo=NUEVO[0])
    PasoOnboarding.objects.filter(accion='drive', descripcion=VIEJO[1]).update(descripcion=NUEVO[1])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_configenvios_cliente_recordatorios_cobro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasoonboarding',
            name='accion',
            field=models.CharField(blank=True, choices=[('', 'Tarea'), ('drive', 'Vincular la carpeta de Drive')], max_length=10),
        ),
        migrations.RunPython(actualizar, migrations.RunPython.noop),
    ]
