# Generated by Django 6.0.4 on 2026-04-27 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('dia_mes', models.PositiveSmallIntegerField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#4fffb0', max_length=12)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_mes', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#7c6fff', max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio'],
            },
        ),
    ]
