# Generated by Django 6.0.4 on 2026-09-29 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventounico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='eventounico',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventounico',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cal_eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventounico',
            index=models.Index(fields=['inicio'], name='evento_inicio_idx'),
        ),
    ]
