# Generated by Django 6.0.4 on 2026-09-30 18:03

from django.db import migrations, models


def copias_viejas_a_ceos(apps, schema_editor):
    """Las copias creadas antes en Google están en el calendario principal de la cuenta, que es AuraTeam CEOs."""
    apps.get_model('calendario', 'EventoUnico').objects.exclude(google_event_id='').update(etiqueta='ceos')


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_eliminar_cliente_mensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(choices=[('ceos', 'AuraTeam CEOs'), ('coberturas', 'Coberturas'), ('operaciones', 'Operaciones'), ('reuniones', 'Reuniones & Briefing')], max_length=12, unique=True)),
                ('calendar_id', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('sync_token', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCalendarioGoogle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('ultima_sync_completa', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('ultimo_error_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventounico',
            name='etiqueta',
            field=models.CharField(choices=[('ceos', 'AuraTeam CEOs'), ('coberturas', 'Coberturas'), ('operaciones', 'Operaciones'), ('reuniones', 'Reuniones & Briefing')], default='operaciones', max_length=12),
        ),
        migrations.AddField(
            model_name='eventounico',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copias_viejas_a_ceos, migrations.RunPython.noop),
    ]
