# Generated by Django 6.0.4 on 2026-09-30 19:58

from django.db import migrations, models


def operaciones_a_historias(apps, schema_editor):
    for modelo in ('EventoUnico', 'CalendarioGoogle'):
        apps.get_model('calendario', modelo).objects.filter(etiqueta='operaciones').update(etiqueta='historias')


def historias_a_operaciones(apps, schema_editor):
    for modelo in ('EventoUnico', 'CalendarioGoogle'):
        apps.get_model('calendario', modelo).objects.filter(etiqueta='historias').update(etiqueta='operaciones')


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_etiquetas_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariogoogle',
            name='etiqueta',
            field=models.CharField(choices=[('ceos', 'AuraTeam CEOs'), ('coberturas', 'Coberturas'), ('historias', 'Historias'), ('posteos', 'Posteos'), ('edicion', 'Edición'), ('reuniones', 'Reuniones & Briefing')], max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='eventounico',
            name='etiqueta',
            field=models.CharField(choices=[('ceos', 'AuraTeam CEOs'), ('coberturas', 'Coberturas'), ('historias', 'Historias'), ('posteos', 'Posteos'), ('edicion', 'Edición'), ('reuniones', 'Reuniones & Briefing')], default='historias', max_length=12),
        ),
        migrations.RunPython(operaciones_a_historias, historias_a_operaciones),
    ]
