# Generated by Django 6.0.4 on 2026-10-02 23:59

from django.db import migrations, models


def marcar_ceos(apps, schema_editor):
    apps.get_model('calendario', 'CalendarioGoogle').objects.filter(etiqueta='ceos').update(privada=True)


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_etiquetas_historias'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariogoogle',
            name='oculta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendariogoogle',
            name='privada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendariogoogle',
            name='etiqueta',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='eventounico',
            name='etiqueta',
            field=models.CharField(default='historias', max_length=40),
        ),
        migrations.RunPython(marcar_ceos, migrations.RunPython.noop),
    ]
